apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app-deploy
spec:
  selector:
    matchLabels:
      app: crud-app
  replicas: 2
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
      - name: crud-app-container
        image: xpadro/k8s-crud-app
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80