apiVersion: v1
kind: Pod
metadata:
  name: crud-app
spec:
  containers:
    - image: xpadro/k8s-crud-app
      name: crud-app-container
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP