apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test-ns
spec:
  serviceAccountName: test-sa
  containers:
  - name: test
    image: alpine:3.2
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent