apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-namespace-role-binding
  namespace: test-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-namespace-role
subjects:
- kind: ServiceAccount
  name: test-sa
  namespace: test-ns