apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: alpine:3.2
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /pod-dir
      name: config-vol
  volumes:
    - name: config-vol
      persistentVolumeClaim:
        claimName: host-pv-claim