apiVersion: v1
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_PASSWORD: dGVzdA==
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres-sql

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: default
  labels:
    app: postgres-sql
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres-sql
spec:
  selector:
    matchLabels:
      app: postgres-sql
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-sql
  name: postgres-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sql
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres-sql
    spec:
      containers:
        - image: postgres:latest
          name: postgres-sql
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdbdatavol
      volumes:
        - name: pgdbdatavol
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-sql
  name: postgres-svc
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 30543
  selector:
    app: postgres-sql
  type: NodePort