apiVersion: v1
kind: Pod
metadata:
  name: test-config
spec:
  containers:
  - name: test-config
    image: alpine:3.2
    imagePullPolicy: Always
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    env:
      - name: PARAM_3
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: param3
  restartPolicy: Never