apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - image: xpadro/hello-world-java
      name: hello-container
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP