apiVersion: v1
kind: Pod
metadata:
  name: test-config
spec:
  containers:
  - name: test-config
    image: alpine:3.2
    imagePullPolicy: Always
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    volumeMounts:
      - name: config-volume
        mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: my-config
  restartPolicy: Never